// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SimpleSocialMedia_ClassLibrary.Entities
{
    [Table("Account")]
    public partial class Account
    {
        public Account()
        {
            Comments = new HashSet<Comment>();
            Posts = new HashSet<Post>();
        }

        [Key]
        public int AccountID { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string AuthToken { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string Username { get; set; }
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string Password { get; set; }

        [InverseProperty("Account")]
        public virtual ICollection<Comment> Comments { get; set; }
        [InverseProperty("Account")]
        public virtual ICollection<Post> Posts { get; set; }
    }
}