// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SimpleSocialMedia_ClassLibrary.Entities
{
    [Table("Chat")]
    public partial class Chat
    {
        public Chat()
        {
            Messages = new HashSet<Message>();
        }

        [Key]
        public int ChatID { get; set; }
        public int Account1ID { get; set; }
        public int Account2ID { get; set; }

        [ForeignKey("Account1ID")]
        [InverseProperty("ChatAccount1s")]
        public virtual Account Account1 { get; set; }
        [ForeignKey("Account2ID")]
        [InverseProperty("ChatAccount2s")]
        public virtual Account Account2 { get; set; }
        [InverseProperty("Chat")]
        public virtual ICollection<Message> Messages { get; set; }
    }
}