// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SimpleSocialMedia_ClassLibrary.Entities
{
    [Table("Comment")]
    public partial class Comment
    {
        [Key]
        public int CommentID { get; set; }
        public int AccountID { get; set; }
        public int PostID { get; set; }
        [Required]
        [StringLength(300)]
        [Unicode(false)]
        public string Text { get; set; }
        public int Likes { get; set; }

        [ForeignKey("AccountID")]
        [InverseProperty("Comments")]
        public virtual Account Account { get; set; }
        [ForeignKey("PostID")]
        [InverseProperty("Comments")]
        public virtual Post Post { get; set; }
    }
}