// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SimpleSocialMedia_ClassLibrary.Entities
{
    public partial class Like
    {
        [Key]
        public int LikeID { get; set; }
        public int AccountID { get; set; }
        public int PostID { get; set; }
        public bool Liked { get; set; }

        [ForeignKey("AccountID")]
        [InverseProperty("Likes")]
        public virtual Account Account { get; set; }
        [ForeignKey("PostID")]
        [InverseProperty("LikesNavigation")]
        public virtual Post Post { get; set; }
    }
}